language: rust
cache: cargo

matrix:
  include:
    # OS compat
    - os: linux
    - os: osx

    # rustc version compat
    - rust: stable
    - rust: 1.40.0
    - rust: beta
    - rust: nightly

    # deployments
    - env: DEPLOY=1 TARGET=x86_64-apple-darwin OPENSSL_STATIC=yes
      script: cargo build --locked --release --target $TARGET
      os: osx
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl OPENSSL_DIR=$HOME/openssl-musl
      before_script: ./ci/travis-musl-openssl.sh
      script: cargo build --locked --release --target $TARGET
      addons:
        apt:
          packages:
          - musl-tools
  allow_failures:
    - rust: nightly

script:
  - cargo build --release --locked --verbose
  - RUST_BACKTRACE=1 cargo test --release --locked --all --verbose
  # Requires PR #321
  #- if [[ "${DIST_SCCACHE}" = "1" ]]; then RUST_BACKTRACE=1 cargo test --all --verbose test_dist_ -- --test-threads 1; fi

before_deploy:
  - "./ci/prep_deploy.sh"

deploy:
  api_key:
    secure: "BiKnB7yxYvqn6ZISVeBjCQFoSeJKjtAxdEAxlZuNF0YKSwPn7/vQaZjASKORu+Q8uGUTRIKaR0HYiF4mbT5nuKPI0VDsHnGFOWvU/QaZazYbNR1RDbPPXiq6buamGwj3GM2VnV49v/1yVexu6+6D1QcR+tES02lJuhKvDMKU+6+0Fw2HcZbO7E1HFfllnPGvgU42fol16B6D12mqHL91K+zhtNZWKGafbmajSqAXpJW6wCSbygeGgpvWW9PuCQ6SzuxTGF8CGyZFZgSA7SjRAMeRkpg5imeIY6uZxytK/ynGuamYZAcvdrePOg2wjogEvCKxcu4RD0uuHmij2a3CPBdkhWksstyuhNkEv34yeLZRu+7Tbt5w2nEQm1+89pVMdCe8IMI08o0g25UaANpmrL+z1VSd17JNt7OetDcrNnSOrcEBDrI03lD4cRpsMqe/tYJGDkmDxfh8sqjKKHN1Wv9VDl/V8ZiL7hB7mB5ZoamrzXrcz3QiWXCJG8U3MHuyhXWpQNLEQ2ZP/n08mZElkhvx4+0rGUWf9l8iQ9e4zwashki7fD3MN9wG8SskfqsHka5c9uCFMl5T18XZ3t+dlu1Xvpccl0NtXpU5ZHTeJJ36I3AFr9m7uMrYrg09Y8l2yySdIHd2emb09dyZk6Z38mE4+r+Dz+I13PH3TZAC2Wk="
  file_glob: true
  file: cargo-crev-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
