[package]
edition = "2018"
name = "crev-lib"
version = "0.1.3"
description = "Scalable, social, Code REView system that we desperately need - core library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/dpc/crev"
homepage = "https://github.com/dpc/crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
app_dirs = "1"
blake2 = "0.8"
chrono = "0.4"
common_failures = "0.1"
derive_builder = "0.7"
digest = "0.8"
failure = "0.1"
git2 = "0.7"
hex = "0.3"
miscreant = "0.4.0-beta2"
rand = "0.5.5"
serde = "1"
serde_cbor = "0.9"
serde_derive = "1"
serde_yaml = "0.8"
tempdir = "0.3"
walkdir = "2"
resiter-dpc-tmp = "0.3"
rprompt = "1"
default = "0.1"

[dependencies.argonautica]
features = ["serde"]
version = "0.1"

[dependencies.crev-common]
path = "../crev-common"
version = "0.1"

[dependencies.crev-data]
path = "../crev-data"
version = "0.1.1"

[dependencies.crev-recursive-digest]
path = "../recursive-digest"
version = "0.1.1"
