[package]
edition = "2018"
name = "crev-lib"
version = "0.15.0"
description = "Scalable, social, Code REView system that we desperately need - core library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/crev-dev/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
chrono = "0.4"
common_failures = "0.1"
crev-common = { path = "../crev-common", version = "0.15.0" }
crev-data = { path = "../crev-data", version = "0.15.0" }
crev-recursive-digest = { path = "../recursive-digest", version = "0.2.1" }
default = "0.1"
directories = "2"
failure = "0.1"
ifmt = "0.2"
git2 = "0.9"
insideout = "0.2"
miscreant = { version = "0.4", features = ["soft-aes"] }
num_cpus = "1"
resiter = "0.3"
rust-argon2 = "0.5"
semver = "0.9"
serde = "1"
serde_cbor = "0.10"
serde_yaml = "0.8"
tempdir = "0.3"
walkdir = "2"
log = "0.4"
