[package]
edition = "2018"
name = "crev-lib"
version = "0.21.0"
description = "Library interface for programmatic access to crate reviews of cargo-crev"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>", "Kornel Lesiński <kornel@geekhood.net>"]
documentation = "https://docs.rs/crev-lib"
repository = "https://github.com/crev-dev/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["code", "review", "assessment", "dependency", "assurance"]
categories = ["development-tools", "database"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
crev-common = { path = "../crev-common", version = "0.21" }
miscreant = "0.5.2"
crev-data = { path = "../crev-data", version = "0.21" }
crev-wot = { path = "../crev-wot", version = "0.21" }
blake2 = "0.8.1"
chrono = { version = "0.4.19", default-features = false }
crev-recursive-digest = "0.4.0"
default = "0.1.2"
directories = { version = "2", package = "directories-next" }
fnv = "1.0.7"
git2 = "0.13.20"
log = "0.4.14"
num_cpus = "1.13.0"
resiter = "0.4.0"
rust-argon2 = "0.8.3"
serde = "1.0.123"
serde_cbor = "0.11.1"
serde_yaml = "0.8.17"
walkdir = "2.3.2"
thiserror = "1.0.26"
rayon = "1.5.1"
