[package]
edition = '2018'
name = "crev-data"
version = "0.17.0"
description = "Scalable, social, Code REView system that we desperately need - data types library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/crev-dev/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
chrono = "0.4"
common_failures = "0.1"
crev-common = { path = "../crev-common", version = "0.16.0" }
derive_builder = "0.7"
typed-builder = "0.3"
ed25519-dalek = "=1.0.0-pre.3"
failure = "0.1"
rand = "0.7"
semver = { version = "0.9", features = [ "serde" ] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
