[package]
edition = '2018'
name = "crev-data"
version = "0.18.0"
description = "Scalable, social, Code REView system that we desperately need - data types library"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
documentation = "https://docs.rs/crev"
repository = "https://github.com/crev-dev/cargo-crev"
homepage = "https://github.com/crev-dev/cargo-crev"
keywords = ["code", "review", "tool", "distributed"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
crev-common = { path = "../crev-common", version = "0.18.0" }
chrono = "0.4.11"
derive_builder = "0.9.0"
ed25519-dalek = "1.0.0"
rand = "0.7.3"
semver = { version = "0.10.0", features = [ "serde" ] }
serde = { version = "1.0.106", features = ["derive"] }
serde_yaml = "0.8.11"
typed-builder = "0.7"
thiserror = "1.0.17"
